name: SoundixStudio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36275
title: Soundix Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#01873d'
    - '#ff0001'
    - '#ffff03'
    - '#f6881c'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
